spring:
  security:
    saml2:
      relyingparty:
        registration:
          keycloak:
            entity-id: saml-poc
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              url: http://localhost:8080/realms/saml-poc/protocol/saml
              binding: POST
              response-url: "http://localhost:9080/logout/saml2/slo"
            assertingparty:
              metadata-uri: "http://localhost:8080/realms/saml-poc/protocol/saml/descriptor"
server:
  port: 9080
